---
- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: all
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Hello world {{ lookup('env','USER') }}"
